### ISSUE TITLE
php error

### ISSUE THREAD

**Issue by radu81** [Spuds/Elk_FancyBox#4]
have a look here: https://www.elkarte.net/community/index.php?topic=1373.msg36131#msg36131

**Comment by Spuds** [comment]
try changing it to ```if (defined('FORUM_VERSION') && substr(FORUM_VERSION, 8, 3) === '1.1')```  Its probably an error from the side entrance via the proxy ... just a guess.

**Comment by radu81** [comment]
only adding the ' ' to FORUM_VERSION seems to work, no more errors in php log and also the image cache works again.
`	if (substr('FORUM_VERSION', 8, 3) === '1.1')`

**Comment by Spuds** [comment]
Using ```'FORUM_VERSION'``` in quotes you are no longer supplying it the value defined by that constant but instead you have supplied it the string FORUM_VERSION.   You are now searching the srting FORUM_VERSION for 1.1 instead of searching the constants value which should be something like ElkArte 1.1.x

Yes it should be quoted in the ```defined``` statement as I showed, but NOT in the ```substr``` it s PHP thing.

**Comment by radu81** [comment]
Thanks for the clarification, I did the edit you suggested and the imagecache is working and there are no errors in php log.

**Comment by Spuds** [comment]
closed in 1.0.7
